name: release
on:
  push:
    branches:
      - main
    tags:
      - v*.*.*

permissions:
  contents: read

#env:
#  HAS_SECRETS: ${{ secrets.NPM_TOKEN != '' }}

jobs:
  ci:
    name: Run CI
    uses: thakyz/eslint-config-nekoboinick/.github/workflows/ci.yml@main
  release:
    needs:
      - ci
    name: Release through Node.JS
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      #- name: Cancel Workflow
      #  if: env.HAS_SECRETS == 'false'
      #  run: echo 'Canceled Workflow'; exit 1
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Setup Node.JS
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903
        with:
          cache: 'npm'
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Semantic Release from NPM
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release --ci
